"""Adicionar colunas ao Usuario

Revision ID: e02f028be490
Revises: e87ce0325573
Create Date: 2025-10-23 00:10:20.710499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e02f028be490'
down_revision = 'e87ce0325573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adotante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sexo', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('idade', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('endereco', sa.String(length=100), nullable=True))
        batch_op.drop_column('cpf')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('rg', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sexo', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('idade', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cidade', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('estado')
        batch_op.drop_column('cidade')
        batch_op.drop_column('idade')
        batch_op.drop_column('sexo')
        batch_op.drop_column('rg')
        batch_op.drop_column('tipo')

    with op.batch_alter_table('adotante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('endereco')
        batch_op.drop_column('idade')
        batch_op.drop_column('sexo')

    # ### end Alembic commands ###
