"""Adicionar CPF e CNPJ ao Usuario

Revision ID: e37d386d0370
Revises: e02f028be490
Create Date: 2025-10-23 00:21:51.860368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e37d386d0370'
down_revision = 'e02f028be490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cnpj', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['cnpj'])
        batch_op.create_unique_constraint(None, ['cpf'])
        batch_op.drop_column('rg')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rg', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('cnpj')
        batch_op.drop_column('cpf')

    # ### end Alembic commands ###
