"""Criando tabelas iniciais

Revision ID: e87ce0325573
Revises: 
Create Date: 2025-10-22 21:56:23.282315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e87ce0325573'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raca', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('localizacao', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('foto', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_column('foto')
        batch_op.drop_column('localizacao')
        batch_op.drop_column('raca')

    # ### end Alembic commands ###
